apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-passenger-trip-frontend
  labels:
    app: java-passenger-trip
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-passenger-trip
      tier: frontend
  template:
    metadata:
      labels:
        app: java-passenger-trip
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: shirmen/java-passenger-trip-frontend
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: PASSENGER_TRIP_API_ADDR
          value: java-passenger-trip-backend:8080
        # This environment variable enables debugging support for the container.
        # Remove this to disable the debug build.
        - name: JAVA_TOOL_OPTIONS
          value: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y
