apiVersion: v1
kind: Service
metadata:
  name: java-passenger-trip-frontend
  labels:
    app: java-passenger-trip
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: java-passenger-trip
    tier: frontend
  ports:
  - port: 80
    targetPort: http-server
