apiVersion: v1
kind: Service
metadata:
  name: reservation-service
  labels:
    app: reservation-service
spec:
#  type: ClusterIP
  type: LoadBalancer
  selector:
    app: reservation-service
  ports:
  - port: 8080
    targetPort: 8080
