apiVersion: v1
kind: Service
metadata:
  name: reservation-service-cassandradb
  labels:
    app: reservation-service
    tier: db
spec:
  ports:
    - port: 9042
      targetPort: 9042
  selector:
    app: reservation-service
    tier: db
