apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation-service
  template:
    metadata:
      labels:
        app: reservation-service
      containers:
        - name: reservation-service
          image: getaneh/reservation-service
          imagePullPolicy: Always
          ports:
            - name: http-server
              containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: RESERVATION_DB_ADDR
              value: "reservation-service-cassandradb:9042"
            # This environment variable enables debugging support for the container.
            # Remove this to disable the debug build.
            - name: JAVA_TOOL_OPTIONS
              value: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y

            - name: RESERVATION_SERVICE_KAFKATOPIC
              valueFrom:
                secretKeyRef:
                  name: reservation-service-secrets
                  key: RESERVATION_SERVICE_KAFKATOPIC

            - name: RESERVATION_SERVICE_KAFKAURI
              valueFrom:
                secretKeyRef:
                  name: reservation-service-secrets
                  key: RESERVATION_SERVICE_KAFKAURI

            - name: SPRING_DATA_CASSANDRA_CONTACT-POINTS
              valueFrom:
                secretKeyRef:
                  name: reservation-service-secrets
                  key: SPRING_DATA_CASSANDRA_CONTACT-POINTS

            - name: SPRING_DATA_CASSANDRA_KEYSPACE-NAME
              valueFrom:
                secretKeyRef:
                  name: reservation-service-secrets
                  key: SPRING_DATA_CASSANDRA_KEYSPACE-NAME

            - name: SPRING_DATA_CASSANDRA_REPLICATION-FACTOR
              valueFrom:
                secretKeyRef:
                  name: reservation-service-secrets
                  key: SPRING_DATA_CASSANDRA_REPLICATION_FACTOR


