apiVersion: v1
kind: Secret
metadata:
  name: trip-registration-service-secrets
type: Opaque
data:
  SERVER_PORT: ODA4MA==

  SPRING_DATA_CASSANDRA_CONTACT-POINTS: dHJpcC1yZWdpc3RyYXRpb24tc2VydmljZS1jYXNzYW5kcmFkYg==
  SPRING_DATA_CASSANDRA_KEYSPACE-NAME: dHJpcHJlZ2lzdHJhdGlvbg==
  SPRING_DATA_CASSANDRA_PORT: OTA0Mg==
  SPRING_DATA_CASSANDRA_REPLICATION_FACTOR: MQ==

  trip-registration_SERVICE_KAFKATOPIC: TkVXUkVTRVJWQVRJT04=
  trip-registration_SERVICE_KAFKAURI: Y2FycG9vbGthZmthOjkwOTI=
#  kafka.bootstrap.servers : Y2FycG9vbGthZmthOjkwOTI=
  kafka.topic.reservation: TkVXUkVTRVJWQVRJT04=
  reservation_service_kafkaUri: Y2FycG9vbGthZmthOjkwOTI=
