apiVersion: v1
kind: Secret
metadata:
  name: java-trip-register-service-secrets
type: Opaque
data:
  SERVER_PORT: ODA4MA==

  SPRING_DATA_CASSANDRA_CONTACT-POINTS: amF2YS1wYXNzZW5nZXItdHJpcC1jYXNzYW5kcmFkYg==
  SPRING_DATA_CASSANDRA_KEYSPACE-NAME: bXlrZXlzcGFjZQ==
  SPRING_DATA_CASSANDRA_PORT: OTA0Mg==
  SPRING_DATA_CASSANDRA_REPLICATION_FACTOR: MQ==

  PASSENGER_TRIP_KAFKATOPIC: cGFzc2VuZ2VyLXRyaXAtdG9waWM=
  PASSENGER_TRIP_KAFKAURI: a2Fma2E6OTA5Mg==
