apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: lferasu/notification-service
        imagePullPolicy: Always
        ports:
            - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: SPRING_DATA_MONGODB_URI
          value: "notificationservice-mongodb:27017"
        - name: SPRING_DATA_MONGODB_DATABASE
          value: "Carpool"

        # This environment variable enables debugging support for the container.
        # Remove this to disable the debug build.
        - name: JAVA_TOOL_OPTIONS
          value: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y

        - name: SPRING_MAIL_HOST
          valueFrom:
              secretKeyRef:
                name: notification-service-secrets
                key: SPRING_MAIL_HOST
        - name: SPRING_MAIL_PORT
          valueFrom:
              secretKeyRef:
                name: notification-service-secrets
                key: SPRING_MAIL_PORT
        - name: SPRING_MAIL_USERNAME
          valueFrom:
              secretKeyRef:
                name: notification-service-secrets
                key: SPRING_MAIL_USERNAME
        - name: SPRING_MAIL_PASSWORD
          valueFrom:
              secretKeyRef:
                name: notification-service-secrets
                key: SPRING_MAIL_PASSWORD
        - name: APP_EMAIL_ADDRESS
          valueFrom:
              secretKeyRef:
                name: notification-service-secrets
                key: APP_EMAIL_ADDRESS
        - name: EMAIL_SUBJECT
          valueFrom:
              secretKeyRef:
                name: notification-service-secrets
                key: EMAIL_SUBJECT
        - name: KAFKA_TOPIC_NOTIFICATION
          valueFrom:
              secretKeyRef:
                name: notification-service-secrets
                key: KAFKA_TOPIC_NOTIFICATION


        - name: KAFKA_TOPIC_NEWRESERVATION
          valueFrom:
              secretKeyRef:
                name: notification-service-secrets
                key: KAFKA_TOPIC_NEWRESERVATION

#        - name: KAFKA_BOOTSTRAP_SERVERS
#          valueFrom:
#              secretKeyRef:
#                name: notification-service-secrets
#                key: KAFKA_BOOTSTRAP_SERVERS

#        - name: NOTFICATION_SERVICE_KAFKAURI
#          valueFrom:
#              secretKeyRef:
#              name: notificationservice-secrets
#              key: NOTFICATION_SERVICE_KAFKAURI

