apiVersion: v1
kind: Service
metadata:
  name: java-passenger-trip-backend
  labels:
    app: java-passenger-trip
    tier: backend
spec:
  type: ClusterIP
#  type: LoadBalancer
  selector:
    app: java-passenger-trip
    tier: backend
  ports:
  - port: 8080
    targetPort: http-server
