################################################################################
# WARNING: This MongoDB deployment is not suitable for production as the data is
# not persistently stored and will go away every time the Pod restarts. Consider
# using a Helm chart that provisions a StatefulSet instead of Deployment.
################################################################################
kind: Deployment
apiVersion: apps/v1
metadata:
  name: java-passenger-trip-cassandradb
  labels:
    app: java-passenger-trip
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-passenger-trip
      tier: db
  template:
    metadata:
      labels:
        app: java-passenger-trip
        tier: db
    spec:
      containers:
        - name: cassandra
          image: cassandra:3
          ports:
            - containerPort: 9042
