apiVersion: v1
kind: Service
metadata:
  name: java-auth-service-backend
  labels:
    app: java-auth-service
    tier: backend
spec:
#  type: ClusterIP
  type: LoadBalancer
  selector:
    app: java-auth-service
    tier: backend
  ports:
  - port: 8080
    targetPort: http-server
