apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth_service
spec:
#  type: ClusterIP
  type: LoadBalancer
  selector:
    app: auth_service
  ports:
  - port: 8080
    targetPort: 8080
