apiVersion: v1
kind: Service
metadata:
  name: notificationservice
  labels:
    app: notificationservice
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app: notificationservice
    tier: backend
  ports:
  - port: 8080
    targetPort: http-server
