apiVersion: v1
kind: Service
metadata:
  name: notificationservice-mongodb
  labels:
    app: java-notificationservice
    tier: db
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: java-notificationservice
    tier: db
