apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: surafel.t.mamo/notification-service
deploy:
  kubectl:
    manifests:
    - manifest/notification-service-deployment.yaml
    - manifest/notification-service-secret.yaml
    - manifest/notification-service.yaml
