apiVersion: v1
kind: Service
metadata:
  name: notificationservice
spec:
  type: NodePort
  selector:
    app: notificationservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
