apiVersion: v1
kind: Service
metadata:
  name: java-passenger-trip-cassandradb
  labels:
    app: java-passenger-trip
    tier: db
spec:
  ports:
    - port: 9042
      targetPort: 9042
  selector:
    app: java-passenger-trip
    tier: db
